// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// bitset_permutation
arma::mat bitset_permutation(Rcpp::LogicalVector x, unsigned int ones, unsigned long permutations);
RcppExport SEXP _uniqueperm_bitset_permutation(SEXP xSEXP, SEXP onesSEXP, SEXP permutationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type ones(onesSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type permutations(permutationsSEXP);
    rcpp_result_gen = Rcpp::wrap(bitset_permutation(x, ones, permutations));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_uniqueperm_bitset_permutation", (DL_FUNC) &_uniqueperm_bitset_permutation, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_uniqueperm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
