// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// bitsetpermute
arma::mat bitsetpermute(Rcpp::LogicalVector x, unsigned long permutations);
RcppExport SEXP _uniqueperm_bitsetpermute(SEXP xSEXP, SEXP permutationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned long >::type permutations(permutationsSEXP);
    rcpp_result_gen = Rcpp::wrap(bitsetpermute(x, permutations));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_uniqueperm_bitsetpermute", (DL_FUNC) &_uniqueperm_bitsetpermute, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_uniqueperm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
