# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bitsetpermute <- function(original, number_permutations) {
    .Call('_uniqueperm_bitsetpermute', PACKAGE = 'uniqueperm', original, number_permutations)
}

